# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0003_remove_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 2, 39, 29, 528609)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 2, 39, 29, 528529)),
        ),
    ]
