# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0004_auto_20171025_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 2, 40, 48, 62225)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 2, 40, 48, 62311)),
        ),
    ]
